#!/bin/bash
#
# UniFi v2 Collector - Complete Installation Script
# Installs UniFi collector for 15 endpoints with systemd integration
# Supports Integration API v1 (12 endpoints) + Legacy API (3 endpoints)
#
# Usage: sudo ./install-collector.sh
#

set -euo pipefail

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Installation paths
INSTALL_BASE="/opt/unifi-collector"
BIN_DIR="${INSTALL_BASE}/bin"
CONFIG_DIR="${INSTALL_BASE}/config"
CACHE_DIR="${INSTALL_BASE}/cache"
LOG_DIR="/var/log/unifi"
SYSTEMD_DIR="/etc/systemd/system"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Collector user
COLLECTOR_USER="unifi-collector"
COLLECTOR_GROUP="unifi-collector"

# 17 endpoints with collection intervals (minutes)
ENDPOINTS=(
    "devices:5"
    "clients:5"
    "networks:15"
    "wifi:15"
    "firewall-zones:15"
    "acl-rules:15"
    "traffic-lists:30"
    "radius-profiles:30"
    "device-tags:30"
    "vpn-servers:30"
    "port-forward:30"
    "wans:60"
    "dpi-categories:1440"
    "dpi-applications:1440"
    "health:60"
    "events:5"
    "alarms:15"
)

# Banner
echo -e "${BLUE}"
echo "═══════════════════════════════════════════════════════"
echo "  UniFi v2 Collector - Complete Installation"
echo "  Integration API v1 + Legacy API Support"
echo "═══════════════════════════════════════════════════════"
echo -e "${NC}"
echo ""

# Check root
if [[ $EUID -ne 0 ]]; then
   echo -e "${RED}Error: This script must be run as root (use sudo)${NC}"
   exit 1
fi

# Step 1: Check prerequisites
echo -e "${YELLOW}[1/9] Checking prerequisites...${NC}"

missing_deps=0
for cmd in curl jq systemctl; do
    if command -v $cmd &> /dev/null; then
        echo "  ✓ $cmd is installed"
    else
        echo -e "  ${RED}✗ $cmd is not installed${NC}"
        missing_deps=1
    fi
done

if [[ $missing_deps -eq 1 ]]; then
    echo ""
    echo -e "${YELLOW}Installing missing dependencies...${NC}"
    if command -v apt-get &> /dev/null; then
        apt-get update -qq && apt-get install -y curl jq systemd
    elif command -v yum &> /dev/null; then
        yum install -y curl jq systemd
    else
        echo -e "${RED}Error: Unable to install dependencies automatically${NC}"
        echo "Please install: curl jq systemd"
        exit 1
    fi
    echo "  ✓ Dependencies installed"
fi

echo ""

# Step 2: Create directories
echo -e "${YELLOW}[2/9] Creating directories...${NC}"
for dir in "$BIN_DIR" "$CONFIG_DIR" "$CACHE_DIR" "$LOG_DIR"; do
    if [[ -d "$dir" ]]; then
        echo "  ✓ Directory exists: $dir"
    else
        mkdir -p "$dir"
        echo "  ✓ Created: $dir"
    fi
done
echo ""

# Step 3: Create service user
echo -e "${YELLOW}[3/9] Creating service user...${NC}"
if id "$COLLECTOR_USER" &>/dev/null; then
    echo "  ✓ User '$COLLECTOR_USER' already exists"
else
    useradd -r -s /bin/false "$COLLECTOR_USER"
    echo "  ✓ User '$COLLECTOR_USER' created"
fi

# Set permissions
chown -R "$COLLECTOR_USER:$COLLECTOR_GROUP" "$INSTALL_BASE" "$LOG_DIR"
chmod 750 "$CONFIG_DIR"
chmod 755 "$BIN_DIR" "$CACHE_DIR" "$LOG_DIR"
echo "  ✓ Permissions set"
echo ""

# Step 4: Install collector script
echo -e "${YELLOW}[4/9] Installing collector script...${NC}"

script_name="unifi-collector.sh"
if [[ ! -f "${SCRIPT_DIR}/${script_name}" ]]; then
    echo -e "${RED}  ✗ Cannot find ${script_name} in current directory${NC}"
    exit 1
fi

cp "${SCRIPT_DIR}/${script_name}" "${BIN_DIR}/${script_name}"
chmod 755 "${BIN_DIR}/${script_name}"
chown "$COLLECTOR_USER:$COLLECTOR_GROUP" "${BIN_DIR}/${script_name}"
echo "  ✓ Installed: ${BIN_DIR}/${script_name}"
echo ""

# Step 5: Configure controllers
echo -e "${YELLOW}[5/9] Configuring UniFi controllers...${NC}"
echo ""

SKIP_CONFIG=false

# Check if config already exists
if [[ -f "${CONFIG_DIR}/controllers.conf" ]] && [[ -s "${CONFIG_DIR}/controllers.conf" ]]; then
    echo "  ℹ Configuration file already exists: ${CONFIG_DIR}/controllers.conf"
    read -p "  Do you want to reconfigure? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "  ✓ Keeping existing configuration"
        SKIP_CONFIG=true
    fi
fi

if [[ "$SKIP_CONFIG" != "true" ]]; then
    echo "  Let's configure your UniFi controller(s)..."
    echo ""

    # Create temp config file
    temp_config=$(mktemp)
    cat > "$temp_config" <<'EOF'
# UniFi Controller Configuration
# Format: COLLECTOR_SITE|CONTROLLER_IP|PORT|SITE_NAME|API_KEY|SITE_UUID (optional)
#
# Note: SITE_UUID is optional - will be auto-discovered from SITE_NAME if not provided
# This makes v2 backward compatible with v1 configuration
#
# Auto-generated by install-collector.sh

EOF

    # Ask for auto-discovery
    read -p "  Do you want to auto-discover sites? (Y/n): " -n 1 -r
    echo
    AUTO_DISCOVER=${REPLY:-Y}

    if [[ $AUTO_DISCOVER =~ ^[Yy]$ ]]; then
        # Auto-discovery mode using Integration API v1
        echo ""
        echo "  📡 Auto-Discovery Mode (Integration API v1)"
        echo "  ────────────────────────────────────────────"

        read -p "  Controller IP address: " CONTROLLER_IP
        read -p "  Controller Port [443]: " CONTROLLER_PORT
        CONTROLLER_PORT=${CONTROLLER_PORT:-443}
        read -sp "  API Key: " API_KEY
        echo ""

        echo ""
        echo "  🔍 Discovering sites on ${CONTROLLER_IP}:${CONTROLLER_PORT}..."

        # Fetch sites from Integration API v1
        sites_response=$(curl -ks -w "\n%{http_code}" \
            -H "X-API-Key: ${API_KEY}" \
            -H "Accept: application/json" \
            --connect-timeout 10 \
            --max-time 30 \
            "https://${CONTROLLER_IP}:${CONTROLLER_PORT}/proxy/network/integration/v1/sites" 2>/dev/null)

        http_code=$(echo "$sites_response" | tail -n1)
        sites_data=$(echo "$sites_response" | sed '$d')

        if [[ "$http_code" == "200" ]]; then
            # Check if response is valid JSON with data array
            if echo "$sites_data" | jq empty 2>/dev/null; then
                site_count=$(echo "$sites_data" | jq '.data | length' 2>/dev/null)

                if [[ "$site_count" -gt 0 ]]; then
                    echo -e "  ${GREEN}✓ Found ${site_count} site(s)${NC}"
                    echo ""

                    # Parse and display sites with UUID
                    echo "$sites_data" | jq -r '.data[] | "\(.desc // .name)|\(.name)|\(.id)"' | while IFS='|' read -r site_desc site_name site_uuid; do
                        echo "    • ${site_desc} (${site_name})"
                        echo "      UUID: ${site_uuid}"

                        # Add to config file with friendly name
                        friendly_name=$(echo "$site_desc" | tr ' ' '_' | tr '[:lower:]' '[:upper:]')
                        echo "${friendly_name}|${CONTROLLER_IP}|${CONTROLLER_PORT}|${site_name}|${API_KEY}|${site_uuid}" >> "$temp_config"
                    done

                    echo ""
                    echo -e "  ${GREEN}✓ Configuration generated successfully${NC}"

                    # Move temp config to final location
                    mv "$temp_config" "${CONFIG_DIR}/controllers.conf"
                    chown "$COLLECTOR_USER:$COLLECTOR_GROUP" "${CONFIG_DIR}/controllers.conf"
                    chmod 600 "${CONFIG_DIR}/controllers.conf"

                else
                    echo -e "  ${RED}✗ No sites found on controller${NC}"
                    rm -f "$temp_config"
                    exit 1
                fi
            else
                echo -e "  ${RED}✗ Invalid JSON response from controller${NC}"
                echo "Response: $sites_data"
                rm -f "$temp_config"
                exit 1
            fi
        else
            echo -e "  ${RED}✗ Failed to connect to controller (HTTP $http_code)${NC}"
            echo "  Please check:"
            echo "    • Controller IP address and port"
            echo "    • API key is valid"
            echo "    • Controller is reachable from this host"
            echo "    • Integration API v1 is enabled"
            rm -f "$temp_config"
            exit 1
        fi
    else
        # Manual configuration mode
        echo ""
        echo "  ✏️  Manual Configuration Mode"
        echo "  ─────────────────────────────"
        echo "  Format: COLLECTOR_SITE|CONTROLLER_IP|PORT|SITE_NAME|API_KEY|[SITE_UUID]"
        echo ""
        echo "  Examples:"
        echo "    With UUID:    MAIN_OFFICE|192.0.2.10|443|default|your-api-key|1234567890abcdef12345678"
        echo "    Without UUID: MAIN_OFFICE|192.0.2.10|443|default|your-api-key"
        echo ""
        echo "  Note: SITE_UUID is optional and will be auto-discovered if not provided"
        echo ""

        while true; do
            read -p "  Enter configuration line (or press Enter to finish): " config_line
            [[ -z "$config_line" ]] && break
            echo "$config_line" >> "$temp_config"
            echo "  ✓ Added"
        done

        # Move temp config to final location
        mv "$temp_config" "${CONFIG_DIR}/controllers.conf"
        chown "$COLLECTOR_USER:$COLLECTOR_GROUP" "${CONFIG_DIR}/controllers.conf"
        chmod 600 "${CONFIG_DIR}/controllers.conf"

        echo ""
        echo "  ✓ Configuration saved"
    fi

    echo ""
    echo "  Configuration file: ${CONFIG_DIR}/controllers.conf"
fi

echo ""

# Step 6: Create systemd template service
echo -e "${YELLOW}[6/9] Creating systemd template service...${NC}"

cat > "${SYSTEMD_DIR}/unifi-collector@.service" <<EOF
[Unit]
Description=UniFi Network API Collector v2 - %i
After=network-online.target
Wants=network-online.target

[Service]
Type=oneshot
ExecStart=${BIN_DIR}/unifi-collector.sh %i
User=${COLLECTOR_USER}
Group=${COLLECTOR_GROUP}
StandardOutput=journal
StandardError=journal
SyslogIdentifier=unifi-collector-%i

# Security hardening
NoNewPrivileges=true
PrivateTmp=true
ProtectSystem=strict
ProtectHome=true
ReadWritePaths=${LOG_DIR} ${CACHE_DIR}

# Resource limits
TimeoutStartSec=120

[Install]
WantedBy=multi-user.target
EOF

echo "  ✓ Created: ${SYSTEMD_DIR}/unifi-collector@.service"
echo ""

# Step 7: Create timers for each endpoint
echo -e "${YELLOW}[7/9] Creating timers for all endpoints...${NC}"

timer_count=0
for endpoint_config in "${ENDPOINTS[@]}"; do
    endpoint="${endpoint_config%%:*}"
    interval="${endpoint_config##*:}"

    timer_file="${SYSTEMD_DIR}/unifi-collector-${endpoint}.timer"

    cat > "$timer_file" <<EOF
[Unit]
Description=UniFi Collector Timer v2 - ${endpoint}
Requires=unifi-collector@${endpoint}.service

[Timer]
OnBootSec=2min
OnUnitActiveSec=${interval}min
AccuracySec=30s
Unit=unifi-collector@${endpoint}.service

[Install]
WantedBy=timers.target
EOF

    if [[ -f "$timer_file" ]]; then
        timer_count=$((timer_count + 1))
        echo "  ✓ Created: unifi-collector-${endpoint}.timer (every ${interval} min)"
    else
        echo -e "  ${RED}✗ Failed: unifi-collector-${endpoint}.timer${NC}"
    fi
done

echo ""
echo -e "  ${GREEN}✓ Successfully created all ${timer_count} timers${NC}"
echo ""

# Step 8: Enable and start timers
echo -e "${YELLOW}[8/9] Enabling and starting timers...${NC}"

systemctl daemon-reload
echo "  ✓ Systemd reloaded"

# Temporarily disable exit on error
set +e

enabled_count=0
started_count=0

for endpoint_config in "${ENDPOINTS[@]}"; do
    endpoint="${endpoint_config%%:*}"
    timer="unifi-collector-${endpoint}.timer"

    if systemctl enable "$timer" 2>/dev/null; then
        enabled_count=$((enabled_count + 1))
    fi

    if systemctl start "$timer" 2>/dev/null; then
        started_count=$((started_count + 1))
    fi
done

echo "  ✓ Enabled ${enabled_count} timers"
echo "  ✓ Started ${started_count} timers"

# Re-enable exit on error
set -e

echo ""

# Step 9: Verification
echo -e "${YELLOW}[9/9] Verifying installation...${NC}"

# Verify directories
if [[ -d "$INSTALL_BASE" && -d "$LOG_DIR" ]]; then
    echo "  ✓ Directories created and accessible"
fi

# Verify script is executable
if [[ -x "${BIN_DIR}/unifi-collector.sh" ]]; then
    echo "  ✓ Collector script is executable"
fi

# Verify timers are active
active_timers=$(systemctl list-timers 'unifi-collector-*' --no-pager 2>/dev/null | grep -c 'unifi-collector' || echo "0")
active_timers=$(echo "$active_timers" | tr -d '\n' | tr -d ' ')
expected_timers=${#ENDPOINTS[@]}

if [[ "$active_timers" -eq "$expected_timers" ]] 2>/dev/null; then
    echo -e "  ${GREEN}✓ All ${active_timers} timers are active${NC}"
elif [[ "$active_timers" -gt 0 ]] 2>/dev/null; then
    echo -e "  ${YELLOW}⚠ Only ${active_timers}/${expected_timers} timers are active${NC}"
else
    echo -e "  ${RED}✗ No timers are active${NC}"
fi

echo ""

# Final status
if [[ "$active_timers" -eq "$expected_timers" ]] 2>/dev/null; then
    echo -e "${GREEN}╔═══════════════════════════════════════════════════════╗${NC}"
    echo -e "${GREEN}║         Installation Complete Successfully!          ║${NC}"
    echo -e "${GREEN}╚═══════════════════════════════════════════════════════╝${NC}"
else
    echo -e "${YELLOW}╔═══════════════════════════════════════════════════════╗${NC}"
    echo -e "${YELLOW}║      Installation Complete with Warnings             ║${NC}"
    echo -e "${YELLOW}╚═══════════════════════════════════════════════════════╝${NC}"
fi

echo ""
echo -e "${BLUE}Next Steps:${NC}"
echo ""
echo "1️⃣  Check timer status:"
echo "   systemctl list-timers 'unifi-collector-*'"
echo ""
echo "2️⃣  Test collector manually:"
echo "   sudo -u ${COLLECTOR_USER} ${BIN_DIR}/unifi-collector.sh devices"
echo ""
echo "3️⃣  View logs:"
echo "   journalctl -u 'unifi-collector@*' -f"
echo ""
echo "4️⃣  Check collected data:"
echo "   ls -lh ${LOG_DIR}/"
echo "   cat ${LOG_DIR}/devices_*.json | jq ."
echo ""
echo "5️⃣  Deploy Azure infrastructure:"
echo "   cd ../Azure"
echo "   ./deploy-v2.sh"
echo ""

echo -e "${YELLOW}Configuration File:${NC}"
echo "${CONFIG_DIR}/controllers.conf"
echo ""
echo "Format: COLLECTOR_SITE|CONTROLLER_IP|PORT|SITE_NAME|API_KEY|SITE_UUID"
echo ""

# Show current timer status
echo -e "${YELLOW}Current Timer Status:${NC}"
systemctl list-timers 'unifi-collector-*' --no-pager 2>/dev/null || true

echo ""
echo -e "${GREEN}Installation completed!${NC}"
echo ""
